server:
  port: 8888
spring:
  jpa:
    show-sql: true
    properties:
      hibernate:
        type: trace
  mvc:
    throw-exception-if-no-handler-found: true

logging:
  level:
    org:
      hibernate:
        type: trace

